import {
  User,
  Student,
  HealthRecord,
  Allergy,
  ChronicCondition,
  VisionAssessment,
  HearingAssessment,
  MedicalHistoryItem,
  Immunization,
  Medication,
  MedicalEvent,
  MedicationGiven,
  HealthCheckup,
  StudentCheckup,
  VaccinationProgram,
  StudentVaccination,
  MedicalSupply,
  MedicalSupplyTransaction,
  MedicationRequest,
  MedicationLog,
} from "../models/types";

// Helper function to generate random ID
const generateId = (): string => {
  return Math.random().toString(36).substring(2) + Date.now().toString(36);
};

// USERS
export const mockUsers: User[] = [
  {
    id: "admin1",
    firstName: "Admin",
    lastName: "User",
    email: "admin@example.com",
    role: "admin",
    phone: "0901234567",
    address: "123 Đường Admin, Quận 1, TP. Hồ Chí Minh",
    profileImage: "https://source.unsplash.com/random/200x200/?portrait",
    createdAt: new Date("2023-01-01"),
    updatedAt: new Date("2023-01-01"),
  },
  {
    id: "nurse1",
    firstName: "Y Tá",
    lastName: "Nguyễn",
    email: "nurse@example.com",
    role: "nurse",
    phone: "0902345678",
    address: "456 Đường Y Tế, Quận 2, TP. Hồ Chí Minh",
    profileImage: "https://source.unsplash.com/random/200x200/?nurse",
    createdAt: new Date("2023-01-02"),
    updatedAt: new Date("2023-01-02"),
  },
  {
    id: "parent1",
    firstName: "Phụ Huynh",
    lastName: "Trần",
    email: "parent@example.com",
    role: "parent",
    phone: "0903456789",
    address: "789 Đường Gia Đình, Quận 3, TP. Hồ Chí Minh",
    profileImage: "https://source.unsplash.com/random/200x200/?father",
    createdAt: new Date("2023-01-03"),
    updatedAt: new Date("2023-01-03"),
  },
  {
    id: "parent2",
    firstName: "Phụ Huynh",
    lastName: "Lê",
    email: "parent2@example.com",
    role: "parent",
    phone: "0904567890",
    address: "101 Đường Gia Đình, Quận 4, TP. Hồ Chí Minh",
    profileImage: "https://source.unsplash.com/random/200x200/?mother",
    createdAt: new Date("2023-01-04"),
    updatedAt: new Date("2023-01-04"),
  },
  {
    id: "teacher1",
    firstName: "Giáo Viên",
    lastName: "Phạm",
    email: "teacher@example.com",
    role: "teacher",
    phone: "0905678901",
    address: "202 Đường Giáo Dục, Quận 5, TP. Hồ Chí Minh",
    profileImage: "https://source.unsplash.com/random/200x200/?teacher",
    createdAt: new Date("2023-01-05"),
    updatedAt: new Date("2023-01-05"),
  },
];

// STUDENTS
export const mockStudents: Student[] = [
  {
    id: "student1",
    firstName: "Học Sinh",
    lastName: "Trần",
    dateOfBirth: new Date("2010-05-15"),
    gender: "male",
    grade: "7",
    class: "7A",
    parentId: "parent1",
    profileImage: "https://source.unsplash.com/random/200x200/?boy",
    healthRecordId: "healthRecord1",
    createdAt: new Date("2023-02-01"),
    updatedAt: new Date("2023-02-01"),
  },
  {
    id: "student2",
    firstName: "Học Sinh",
    lastName: "Lê",
    dateOfBirth: new Date("2011-08-20"),
    gender: "female",
    grade: "6",
    class: "6B",
    parentId: "parent2",
    profileImage: "https://source.unsplash.com/random/200x200/?girl",
    healthRecordId: "healthRecord2",
    createdAt: new Date("2023-02-02"),
    updatedAt: new Date("2023-02-02"),
  },
  {
    id: "student3",
    firstName: "Học Sinh",
    lastName: "Phạm",
    dateOfBirth: new Date("2009-12-10"),
    gender: "male",
    grade: "8",
    class: "8C",
    parentId: "parent1",
    profileImage: "https://source.unsplash.com/random/200x200/?teenager",
    healthRecordId: "healthRecord3",
    createdAt: new Date("2023-02-03"),
    updatedAt: new Date("2023-02-03"),
  },
];

// ALLERGIES
export const mockAllergies: Record<string, Allergy[]> = {
  healthRecord1: [
    {
      id: "allergy1",
      name: "Dị ứng hải sản",
      severity: "moderate",
      symptoms: "Phát ban, ngứa, khó thở nhẹ",
      treatment: "Tránh ăn hải sản, dùng thuốc kháng histamine khi cần",
      dateIdentified: new Date("2020-03-15"),
    },
  ],
  healthRecord2: [
    {
      id: "allergy2",
      name: "Dị ứng phấn hoa",
      severity: "mild",
      symptoms: "Hắt hơi, chảy nước mũi, ngứa mắt",
      treatment: "Thuốc kháng histamine, tránh tiếp xúc với phấn hoa",
      dateIdentified: new Date("2021-04-10"),
    },
    {
      id: "allergy3",
      name: "Dị ứng đậu phộng",
      severity: "severe",
      symptoms: "Phát ban, sưng môi và lưỡi, khó thở",
      treatment: "Tránh tiếp xúc với đậu phộng, mang theo Epipen",
      dateIdentified: new Date("2019-07-22"),
    },
  ],
  healthRecord3: [],
};

// CHRONIC CONDITIONS
export const mockChronicConditions: Record<string, ChronicCondition[]> = {
  healthRecord1: [
    {
      id: "condition1",
      name: "Hen suyễn",
      diagnosisDate: new Date("2019-05-10"),
      medications: [
        {
          id: "medication1",
          name: "Ventolin",
          dosage: "2 nhát xịt",
          frequency: "Khi cần, không quá 4 lần mỗi ngày",
          startDate: new Date("2019-05-12"),
          requestedByParent: true,
          approved: true,
          approvedBy: "nurse1",
          approvedAt: new Date("2019-05-12"),
        },
      ],
      notes: "Hen nhẹ, chủ yếu xảy ra khi tập thể dục hoặc khi thời tiết lạnh",
    },
  ],
  healthRecord2: [],
  healthRecord3: [
    {
      id: "condition2",
      name: "Tiểu đường týp 1",
      diagnosisDate: new Date("2018-12-05"),
      medications: [
        {
          id: "medication2",
          name: "Insulin",
          dosage: "Theo chỉ dẫn của bác sĩ",
          frequency: "Trước bữa ăn",
          startDate: new Date("2018-12-07"),
          requestedByParent: true,
          approved: true,
          approvedBy: "nurse1",
          approvedAt: new Date("2018-12-07"),
        },
      ],
      notes: "Cần theo dõi đường huyết định kỳ",
    },
  ],
};

// VISION ASSESSMENTS
export const mockVisionAssessments: Record<string, VisionAssessment> = {
  healthRecord1: {
    id: "vision1",
    date: new Date("2023-03-15"),
    leftEye: 0.8,
    rightEye: 0.9,
    wearsCorrective: false,
    notes: "Thị lực tốt, không cần kính",
  },
  healthRecord2: {
    id: "vision2",
    date: new Date("2023-03-15"),
    leftEye: 0.6,
    rightEye: 0.5,
    wearsCorrective: true,
    notes: "Đã được đo kính, cần đeo kính khi học bài",
  },
  healthRecord3: {
    id: "vision3",
    date: new Date("2023-03-15"),
    leftEye: 0.7,
    rightEye: 0.7,
    wearsCorrective: false,
  },
};

// HEARING ASSESSMENTS
export const mockHearingAssessments: Record<string, HearingAssessment> = {
  healthRecord1: {
    id: "hearing1",
    date: new Date("2023-03-15"),
    leftEar: "normal",
    rightEar: "normal",
  },
  healthRecord2: {
    id: "hearing2",
    date: new Date("2023-03-15"),
    leftEar: "normal",
    rightEar: "mild loss",
    notes: "Giảm nhẹ thính lực ở tai phải, nên theo dõi",
  },
  healthRecord3: {
    id: "hearing3",
    date: new Date("2023-03-15"),
    leftEar: "normal",
    rightEar: "normal",
  },
};

// MEDICAL HISTORY
export const mockMedicalHistory: Record<string, MedicalHistoryItem[]> = {
  healthRecord1: [
    {
      id: "history1",
      date: new Date("2021-07-10"),
      condition: "Gãy tay",
      treatment: "Bó bột 6 tuần",
      hospital: "Bệnh viện Nhi Đồng",
      doctor: "Bác sĩ Nguyễn Văn A",
      notes: "Tai nạn khi chơi thể thao, đã hồi phục hoàn toàn",
    },
  ],
  healthRecord2: [
    {
      id: "history2",
      date: new Date("2022-04-15"),
      condition: "Viêm phổi",
      treatment: "Kháng sinh và nghỉ ngơi",
      hospital: "Bệnh viện Nhi Đồng 2",
      doctor: "Bác sĩ Trần Thị B",
    },
  ],
  healthRecord3: [
    {
      id: "history3",
      date: new Date("2020-11-20"),
      condition: "Phẫu thuật ruột thừa",
      treatment: "Phẫu thuật nội soi",
      hospital: "Bệnh viện Chợ Rẫy",
      doctor: "Bác sĩ Lê Văn C",
      notes: "Đã hồi phục tốt, không có biến chứng",
    },
  ],
};

// IMMUNIZATIONS
export const mockImmunizations: Record<string, Immunization[]> = {
  healthRecord1: [
    {
      id: "imm1",
      name: "Vắc-xin MMR (Sởi, Quai bị, Rubella)",
      date: new Date("2018-05-10"),
      administered: true,
      administeredBy: "Bệnh viện Nhi Đồng",
      lotNumber: "MMR20180510",
    },
    {
      id: "imm2",
      name: "Vắc-xin HPV",
      date: new Date("2023-06-15"),
      dueDate: new Date("2023-12-15"),
      administered: true,
      administeredBy: "Y tá Nguyễn",
      location: "Trường THCS Nguyễn Huệ",
      lotNumber: "HPV20230615",
      notes: "Mũi 1/3",
    },
  ],
  healthRecord2: [
    {
      id: "imm3",
      name: "Vắc-xin MMR (Sởi, Quai bị, Rubella)",
      date: new Date("2018-06-12"),
      administered: true,
      administeredBy: "Bệnh viện Nhi Đồng 2",
      lotNumber: "MMR20180612",
    },
  ],
  healthRecord3: [
    {
      id: "imm4",
      name: "Vắc-xin MMR (Sởi, Quai bị, Rubella)",
      date: new Date("2018-04-15"),
      administered: true,
      administeredBy: "Bệnh viện Chợ Rẫy",
      lotNumber: "MMR20180415",
    },
    {
      id: "imm5",
      name: "Vắc-xin HPV",
      date: new Date("2023-06-15"),
      dueDate: new Date("2023-12-15"),
      administered: true,
      administeredBy: "Y tá Nguyễn",
      location: "Trường THCS Nguyễn Huệ",
      lotNumber: "HPV20230615",
      notes: "Mũi 1/3",
    },
  ],
};

// HEALTH RECORDS
export const mockHealthRecords: HealthRecord[] = [
  {
    id: "healthRecord1",
    studentId: "student1",
    height: 155,
    weight: 48,
    bloodType: "O+",
    allergies: mockAllergies["healthRecord1"],
    chronicConditions: mockChronicConditions["healthRecord1"],
    visionAssessment: mockVisionAssessments["healthRecord1"],
    hearingAssessment: mockHearingAssessments["healthRecord1"],
    medicalHistory: mockMedicalHistory["healthRecord1"],
    immunizations: mockImmunizations["healthRecord1"],
    lastUpdated: new Date("2023-03-15"),
  },
  {
    id: "healthRecord2",
    studentId: "student2",
    height: 145,
    weight: 40,
    bloodType: "A+",
    allergies: mockAllergies["healthRecord2"],
    chronicConditions: mockChronicConditions["healthRecord2"],
    visionAssessment: mockVisionAssessments["healthRecord2"],
    hearingAssessment: mockHearingAssessments["healthRecord2"],
    medicalHistory: mockMedicalHistory["healthRecord2"],
    immunizations: mockImmunizations["healthRecord2"],
    lastUpdated: new Date("2023-03-15"),
  },
  {
    id: "healthRecord3",
    studentId: "student3",
    height: 165,
    weight: 55,
    bloodType: "B+",
    allergies: mockAllergies["healthRecord3"],
    chronicConditions: mockChronicConditions["healthRecord3"],
    visionAssessment: mockVisionAssessments["healthRecord3"],
    hearingAssessment: mockHearingAssessments["healthRecord3"],
    medicalHistory: mockMedicalHistory["healthRecord3"],
    immunizations: mockImmunizations["healthRecord3"],
    lastUpdated: new Date("2023-03-15"),
  },
];

// MEDICAL EVENTS
export const mockMedicalEvents: MedicalEvent[] = [
  {
    id: "event1",
    studentId: "student1",
    date: new Date("2023-04-10T09:30:00"),
    type: "injury",
    description: "Té ngã trong giờ thể dục",
    symptoms: ["Đau đầu gối", "Xước da"],
    treatment: "Rửa vết thương, băng vết thương, nghỉ ngơi",
    medicationsGiven: [
      {
        id: "medGiven1",
        medicationId: "medication3",
        medicationName: "Paracetamol",
        dosage: "1 viên",
        time: new Date("2023-04-10T09:45:00"),
        administeredBy: "Y tá Nguyễn",
      },
    ],
    outcome: "resolved",
    attendedBy: "Y tá Nguyễn",
    notifiedParent: true,
    notifiedAt: new Date("2023-04-10T10:00:00"),
    parentResponse: "Đã nhận thông tin",
  },
  {
    id: "event2",
    studentId: "student2",
    date: new Date("2023-04-15T11:00:00"),
    type: "illness",
    description: "Sốt và đau đầu trong lớp",
    symptoms: ["Sốt", "Đau đầu", "Mệt mỏi"],
    treatment: "Uống thuốc hạ sốt, nghỉ ngơi trong phòng y tế",
    medicationsGiven: [
      {
        id: "medGiven2",
        medicationId: "medication3",
        medicationName: "Paracetamol",
        dosage: "1 viên",
        time: new Date("2023-04-15T11:15:00"),
        administeredBy: "Y tá Nguyễn",
      },
    ],
    outcome: "sent home",
    attendedBy: "Y tá Nguyễn",
    notifiedParent: true,
    notifiedAt: new Date("2023-04-15T11:30:00"),
    parentResponse: "Sẽ đến đón con về",
    notes: "Phụ huynh đã đón lúc 12:15",
  },
  {
    id: "event3",
    studentId: "student3",
    date: new Date("2023-05-20T13:45:00"),
    type: "emergency",
    description: "Cơn hen suyễn",
    symptoms: ["Khó thở", "Thở khò khè", "Lo lắng"],
    treatment: "Sử dụng thuốc xịt hen, theo dõi",
    medicationsGiven: [
      {
        id: "medGiven3",
        medicationId: "medication1",
        medicationName: "Ventolin",
        dosage: "2 nhát xịt",
        time: new Date("2023-05-20T13:50:00"),
        administeredBy: "Y tá Nguyễn",
      },
    ],
    outcome: "resolved",
    attendedBy: "Y tá Nguyễn",
    notifiedParent: true,
    notifiedAt: new Date("2023-05-20T14:00:00"),
    parentResponse: "Đã nhận thông tin, sẽ theo dõi ở nhà",
  },
];

// HEALTH CHECKUPS
export const mockHealthCheckups: HealthCheckup[] = [
  {
    id: "checkup1",
    type: "routine",
    schoolYear: "2023-2024",
    scheduledDate: new Date("2023-09-15"),
    status: "completed",
    students: [
      {
        id: "studentCheckup1",
        studentId: "student1",
        height: 156,
        weight: 49,
        bmi: 20.1,
        visionLeft: 0.8,
        visionRight: 0.9,
        hearingLeft: "normal",
        hearingRight: "normal",
        bloodPressure: "110/70",
        pulse: 75,
        temperature: 36.5,
        notes: "Sức khỏe tốt",
        referralNeeded: false,
        parentNotified: true,
      },
      {
        id: "studentCheckup2",
        studentId: "student2",
        height: 146,
        weight: 41,
        bmi: 19.2,
        visionLeft: 0.5,
        visionRight: 0.5,
        hearingLeft: "normal",
        hearingRight: "mild loss",
        bloodPressure: "105/65",
        pulse: 80,
        temperature: 36.6,
        notes: "Thị lực kém, cần đo kính mới",
        recommendations: "Nên đi khám mắt và cập nhật kính mới",
        referralNeeded: true,
        referralReason: "Kiểm tra thị lực",
        parentNotified: true,
        parentResponse: "Sẽ đưa con đi khám",
      },
    ],
    conductor: "Y tá Nguyễn",
    notes: "Kiểm tra sức khỏe đầu năm học",
  },
  {
    id: "checkup2",
    type: "specialized",
    schoolYear: "2023-2024",
    scheduledDate: new Date("2023-10-20"),
    status: "scheduled",
    students: [],
    conductor: "Y tá Nguyễn",
    notes: "Kiểm tra răng miệng",
  },
];

// VACCINATION PROGRAMS
export const mockVaccinationPrograms: VaccinationProgram[] = [
  {
    id: "vaccination1",
    name: "Tiêm vắc-xin HPV",
    vaccineType: "HPV",
    targetGrades: ["7", "8"],
    scheduledDate: new Date("2023-06-15"),
    consentDeadline: new Date("2023-06-01"),
    status: "completed",
    students: [
      {
        id: "studentVacc1",
        studentId: "student1",
        consentGiven: true,
        consentGivenAt: new Date("2023-05-20"),
        consentGivenBy: "parent1",
        administered: true,
        administeredAt: new Date("2023-06-15T09:30:00"),
        administeredBy: "Y tá Nguyễn",
        lotNumber: "HPV20230615-001",
        sideEffects: ["Đau tại chỗ tiêm"],
        followUpNeeded: false,
      },
      {
        id: "studentVacc3",
        studentId: "student3",
        consentGiven: true,
        consentGivenAt: new Date("2023-05-22"),
        consentGivenBy: "parent1",
        administered: true,
        administeredAt: new Date("2023-06-15T10:15:00"),
        administeredBy: "Y tá Nguyễn",
        lotNumber: "HPV20230615-003",
        followUpNeeded: false,
      },
    ],
    notes: "Chương trình tiêm chủng HPV mũi 1",
  },
  {
    id: "vaccination2",
    name: "Tiêm vắc-xin Viêm não Nhật Bản",
    vaccineType: "Viêm não Nhật Bản",
    targetGrades: ["6"],
    scheduledDate: new Date("2023-11-10"),
    consentDeadline: new Date("2023-10-25"),
    status: "consent_collection",
    students: [
      {
        id: "studentVacc2",
        studentId: "student2",
        consentGiven: false,
        administered: false,
        followUpNeeded: false,
      },
    ],
    notes: "Đang thu thập phiếu đồng ý",
  },
];

// MEDICAL SUPPLIES
export const mockMedicalSupplies: MedicalSupply[] = [
  {
    id: "supply1",
    name: "Paracetamol",
    category: "medication",
    quantity: 50,
    unit: "viên",
    expiryDate: new Date("2025-06-30"),
    locationStored: "Tủ thuốc P1",
    minimumStockLevel: 20,
    lastUpdated: new Date("2023-08-01"),
  },
  {
    id: "supply2",
    name: "Băng gạc",
    category: "first aid",
    quantity: 30,
    unit: "cuộn",
    locationStored: "Tủ y tế P2",
    minimumStockLevel: 10,
    lastUpdated: new Date("2023-08-01"),
  },
  {
    id: "supply3",
    name: "Oxy già",
    category: "first aid",
    quantity: 5,
    unit: "chai",
    expiryDate: new Date("2024-12-31"),
    locationStored: "Tủ y tế P2",
    minimumStockLevel: 2,
    lastUpdated: new Date("2023-08-01"),
  },
  {
    id: "supply4",
    name: "Nhiệt kế",
    category: "equipment",
    quantity: 8,
    unit: "cái",
    locationStored: "Tủ y tế P1",
    minimumStockLevel: 3,
    lastUpdated: new Date("2023-08-01"),
  },
];

// MEDICAL SUPPLY TRANSACTIONS
export const mockMedicalSupplyTransactions: MedicalSupplyTransaction[] = [
  {
    id: "transaction1",
    supplyId: "supply1",
    type: "restock",
    quantity: 50,
    date: new Date("2023-08-01"),
    performedBy: "nurse1",
    reason: "Nhập thuốc mới",
  },
  {
    id: "transaction2",
    supplyId: "supply1",
    type: "use",
    quantity: 1,
    date: new Date("2023-04-15T11:15:00"),
    performedBy: "nurse1",
    eventId: "event2",
    reason: "Cấp thuốc cho học sinh bị sốt",
  },
  {
    id: "transaction3",
    supplyId: "supply2",
    type: "restock",
    quantity: 30,
    date: new Date("2023-08-01"),
    performedBy: "nurse1",
    reason: "Nhập vật tư y tế mới",
  },
  {
    id: "transaction4",
    supplyId: "supply2",
    type: "use",
    quantity: 1,
    date: new Date("2023-04-10T09:45:00"),
    performedBy: "nurse1",
    eventId: "event1",
    reason: "Băng bó vết thương",
  },
];

export const medicationRequests: MedicationRequest[] = [
  {
    id: "1",
    studentId: "1",
    studentName: "Nguyen Van An",
    parentId: "5",
    medicationName: "Paracetamol",
    dosage: "500mg, 1 viên",
    instructions: "Uống sau bữa trưa",
    daysRequired: 3,
    startDate: new Date("2023-06-01"),
    endDate: new Date("2023-06-03"),
    status: "received",
    receivedBy: "3",
    receivedAt: new Date("2023-06-01T08:30:00"),
    notes: "Học sinh bị sốt nhẹ",
    createdAt: new Date("2023-05-31T20:00:00"),
    updatedAt: new Date("2023-06-01T08:30:00"),
  },
  {
    id: "2",
    studentId: "2",
    studentName: "Le Thi Binh",
    parentId: "6",
    medicationName: "Vitamin C",
    dosage: "250mg, 1 viên",
    instructions: "Uống sau bữa sáng",
    daysRequired: 7,
    startDate: new Date("2023-06-02"),
    endDate: new Date("2023-06-08"),
    status: "requested",
    notes: "Bổ sung vitamin hàng ngày",
    createdAt: new Date("2023-06-01T19:45:00"),
    updatedAt: new Date("2023-06-01T19:45:00"),
  },
  {
    id: "3",
    studentId: "3",
    studentName: "Pham Van Cuong",
    parentId: "7",
    medicationName: "Amoxicillin",
    dosage: "250mg, 1 viên",
    instructions: "Uống sau bữa sáng và tối",
    daysRequired: 5,
    startDate: new Date("2023-06-01"),
    endDate: new Date("2023-06-05"),
    status: "completed",
    receivedBy: "3",
    receivedAt: new Date("2023-06-01T08:15:00"),
    notes: "Điều trị nhiễm trùng tai",
    createdAt: new Date("2023-05-31T21:30:00"),
    updatedAt: new Date("2023-06-05T16:00:00"),
  },
];

export const medicationLogs: MedicationLog[] = [
  {
    id: "1",
    medicationRequestId: "1",
    studentId: "1",
    medicationName: "Paracetamol",
    administeredAt: new Date("2023-06-01T12:30:00"),
    administeredBy: "Nguyen Thi Y Ta",
    dosage: "500mg, 1 viên",
    studentConditionBefore: "Nhiệt độ 37.5°C",
    studentConditionAfter: "Giảm nhiệt độ, học sinh cảm thấy khỏe hơn",
    notes: "Học sinh uống thuốc đầy đủ",
  },
  {
    id: "2",
    medicationRequestId: "1",
    studentId: "1",
    medicationName: "Paracetamol",
    administeredAt: new Date("2023-06-02T12:30:00"),
    administeredBy: "Nguyen Thi Y Ta",
    dosage: "500mg, 1 viên",
    studentConditionBefore: "Bình thường",
    studentConditionAfter: "Bình thường",
    notes: "Học sinh uống thuốc đầy đủ",
  },
  {
    id: "3",
    medicationRequestId: "3",
    studentId: "3",
    medicationName: "Amoxicillin",
    administeredAt: new Date("2023-06-01T08:45:00"),
    administeredBy: "Nguyen Thi Y Ta",
    dosage: "250mg, 1 viên",
    studentConditionBefore: "Học sinh than đau tai",
    studentConditionAfter: "Đau tai giảm",
    notes: "Học sinh uống thuốc đầy đủ",
  },
];
